### ISSUE TITLE
您好！ LIMS(实验室管理系统)有完整且较新的系统吗？ 可以付费

### ISSUE THREAD

**Issue by xian107** [mengyunzhi/labManageSystem#191]
您好！ LIMS(实验室管理系统)有完整且较新的系统吗？ 可以付费

**Comment by teacherpan** [comment]
> 您好！ LIMS(实验室管理系统)有完整且较新的系统吗？ 可以付费

该系统是当初学习完thinkphp后团队内部的练手系统，很抱歉尚无完整或是较新版本。
